language: node_js
node_js:
- '0.11'
- '5.0'
- '6.0'
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  - provider: npm
    email: tituswormer@gmail.com
    api_key:
      secure: lueTq2a6EaQCtroieXyuk0MCe+0Kwx7dqAzEvggPvRV/iXRLNtt+DxS9GlAZQERS4mUzZTCLDYyoLt2UalLSAA9h20ALSpc3GLBLLPJsJzYXQE0QyoojLJjRb/OP6Yr/gRhnTvIUWfd6xyF1TU+nrbZ+1lhQZeOvGCPuHxe+AGY=
    on:
      tags: true
      node: '5.0'
  - provider: releases
    api_key:
      secure: Zi49QPpGdFZC25Ac0p50UO4emA2DzNHMgs/ZFMCKmvuEZgSJEDuoJvuMKHcfbFvSbqGhQI3k/XIZUPDoC64x8nxrY5YFwgz93ti+X3DrNDGYrVi89k3uzoF/VLgv8Jl0/BDtBr/Sx6fnF5Pbqviz06NjxCEX/7rqqIcWVLDtltw=
    file:
      - "array-iterate.js"
      - "array-iterate.min.js"
    on:
      tags: true
      node: '6.0'
