language: node_js
node_js:
  - lts/dubnium
  - node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: U/krLVchHKzXs7ZljsnpIFaQHYhjVvc52ptGmK7Kfr7BF8AdGF78EJ+WLaJhc8umJ4EKazVHDePE6xGFDNv++D/5XFLSCyrvRKuZa9M3ZCkQRrNM59yg21wLMfbN/MCcfCqf3jZRJ/alFVGNzMQfwuJJn6nshJ588dkEa829eOQ=
  file:
    - 'array-iterate.js'
    - 'array-iterate.min.js'
  on:
    tags: true
